### ISSUE TITLE
Bug/Feature Request: Add listener to tab changes

### ISSUE THREAD

**Issue by PassionPenguin** [jasonlong/isometric-contributions#151] opened 2021-03-08 12:23 UTC
options hid after changing years of contribution graph

maybe you can add a listener to these tabs lol :)

https://user-images.githubusercontent.com/41184947/110320986-0b46ef00-804c-11eb-9e3d-e93b034e642d.mov

**Comment by jasonlong** [comment] 2021-03-08 14:21
This one is a duplicate of #57 which I just reopened since I broke the previous fix during a recent refactor. I'm going to close this one in favor of that for now.

**Closed by jasonlong** 2021-03-08 14:21 UTC
